FROM onestone/pp-ubuntu-standard:saucy

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq aptitude automake build-essential byobu curl git htop libboost-all-dev libqt4-gui links mc mercurial python-pip software-properties-common tcptraceroute transmission-gtk transmission-qt && apt-get clean
